dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}